# Generated by Django 3.0.7 on 2020-07-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200701_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='game',
            name='thumb_path',
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(null='djangodbmodelsfieldscharfield', unique=True),
            preserve_default='djangodbmodelsfieldscharfield',
        ),
    ]
